FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm i

# Copy frontend code
COPY frontend/ .

# Set default environment variable
ENV VITE_API_URL=http://localhost:8000/api/v1

# Expose port
EXPOSE 5173

# Start Vite dev server
CMD ["npm", "run", "dev"]
