export interface Agent {
  id: string
  name: string
  role: string
  runningDescription: string
  requiresApproval?: boolean
  systemPrompt: string
}

export interface AgentStep {
  agentId: string
  status: 'pending' | 'running' | 'awaiting-approval' | 'done'
  output?: string
}

export const AGENTS: Agent[] = [
  {
    id: 'legal-researcher',
    name: 'Legal Researcher',
    role: 'Identifies applicable Indian laws and sections',
    runningDescription: 'Scanning Indian statutes, IPC sections, Consumer Protection Act, and Kerala High Court precedents relevant to your complaint…',
    requiresApproval: true,
    systemPrompt: `You are an expert in Indian law with deep knowledge of IPC, CrPC, Consumer Protection Act, RTI Act, IT Act, and other central/state legislation.

Given a structured complaint, identify:
1. Applicable acts and specific sections
2. Whether a cognizable or non-cognizable offence is involved
3. Relevant precedents from Indian courts
4. Jurisdiction (which court/forum has authority)

Always cite specific section numbers.`,
  },
  {
    id: 'document-drafter',
    name: 'Document Drafter',
    role: 'Generates a structured legal petition',
    runningDescription: 'Composing a formal legal petition based on research findings, following Indian court formatting standards and Kerala jurisdiction guidelines…',
    systemPrompt: `You are a legal document specialist. Given research findings, draft a formal legal petition following Indian court standards.

1. Use proper legal language and formatting
2. Address the correct authority (court/forum)
3. Cite all relevant sections identified in research
4. Include prayer/relief sought
5. Follow Kerala High Court formatting where applicable`,
  },
  {
    id: 'viability-assessor',
    name: 'Viability Assessor',
    role: 'Audits the draft and evaluates case strength',
    runningDescription: 'Reviewing the drafted petition for legal accuracy, assessing case viability, and verifying Kerala-specific jurisdictional compliance…',
    requiresApproval: true,
    systemPrompt: `You are a senior Indian advocate with 20 years of litigation experience. Given a complaint and the applicable laws, assess:

1. Strength of the case (Strong / Moderate / Weak) with reasoning
2. Key evidence needed to proceed
3. Potential counterarguments the respondent may raise
4. Realistic outcome probability

Be honest and direct. Do not give false hope.`,
  },
]

export const DUMMY_OUTPUT = `## Assessment Summary

### Grounds for Complaint
Based on your situation, you **have valid grounds** to file a formal complaint under Indian law.

---

### Applicable Laws

| Act | Section | Relevance |
|-----|---------|-----------|
| Indian Penal Code | §420 | Cheating and dishonestly inducing delivery of property |
| Consumer Protection Act, 2019 | §35 | Filing complaint before District Commission |
| IT Act, 2000 | §66C | Identity theft (if applicable) |

---

### Case Viability: **Moderate → Strong**

Your case has a reasonable chance of success provided you can produce:
- Written communication (emails, messages) with the respondent
- Proof of payment / transaction records
- Any contract or agreement signed

> ⚠️ The absence of a written contract weakens the case but does not eliminate it. Witness testimony can substitute.

---

### Recommended Next Steps

1. **Within 7 days** — File a written complaint at your local police station under §420 IPC. Request a copy of the FIR.
2. **Simultaneously** — File a consumer complaint at the District Consumer Disputes Redressal Commission if the dispute involves goods/services.
3. **Gather** — All transaction receipts, screenshots of conversations, and any witnesses.
4. **Legal aid** — Given the complexity, consulting a lawyer is advisable. You may be eligible for free legal aid under the *Legal Services Authorities Act, 1987*.

---

*This assessment is generated by an AI and does not constitute legal advice. Please consult a qualified advocate before taking action.*`
